---
title: 'Class 6: R Functions'
author: "Mary Garcia"
date: "April 18, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### About
This is my **class 6** R markdown document with my *code* and notes for the day.

```{r}
plot(1:10, type ="l", col="blue")
```

## Reading in files practice

There are 3 files to read.

```{r}
read.table("test1.txt", header=TRUE, sep=",")
# Or read.csv("test1.txt")
```

```{r}
read.table("test2.txt", header= TRUE, sep="$")
```

```{r}
read.table("test3.txt")
```

```{r}
read.table("https://bioboot.github.io/bimm143_S19/class-material/test2.txt", header=TRUE, sep="$")
```


## Functions

Our first silly function example:

```{r}
add <- function(x, y=1) {
 # The body!!
 x + y
}
```

```{r}
#add( x=1, y="b")
```

```{r}
#add(1,2,3)
```

```{r}
add( x=c(1,2,3), y=4)
```

```{r}
c(1,2,3) + 4
```

```{r}
add(100)
```

```{r}
add(10, y=10)
```



### another example

```{r}
rescale <- function(x, na.rm = TRUE) {
 rng <-range(x, na.rm = TRUE)
 (x - rng[1]) / (rng[2] - rng[1])
}
rescale(1:10)
```

```{r}
rescale2 <- function(x, na.rm = TRUE) {
  if(!is.numeric(x)) {
    stop("You need to give only numbers please")
  }
 rng <-range(x, na.rm = na.rm)
 (x - rng[1]) / (rng[2] - rng[1])
}
```

```{r}
#rescale2(c(1,10,"string"))
```

```{r}
rescale2( c(1,3,NA,10), na.rm = FALSE)
```


```{r}
rescale(1:10)
```

```{r}
# How would you get your function to work here… -> add na.rm = TRUE
rescale( c(1,2,NA,3,10) )
```

```{r}
# What should your function do here?
#rescale( c(1,10,"string") )

```



```{r}
x <- c(1,2,NA,3,10)
 rng <-range(x, na.rm = TRUE)
 rng
 (x - rng[1]) / (rng[2] - rng[1])
```

```{r}
range(c(1,2,3,10))
```





```{r}
rescale3 <- function(x, na.rm=TRUE, plot=TRUE) {
 rng <-range(x, na.rm=na.rm)
print("Hello")
 answer <- (x - rng[1]) / (rng[2] - rng[1])
 #return(answer) <- Put this at the end of your script to apply rest of the script
 print("is it me you are looking for?")
 if(plot) {
 plot(answer, typ="b", lwd=4)
   print("Please don't sing again...")
 }
 print("I can see it in ...")
 return(answer)
}
```

```{r}
rescale3( c(1,3,NA,10))
```

```{r}
rescale3( c(1,3,NA,10), plot = TRUE)
```







